services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: games
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: games
    ports:
      - "3306:3306"
    volumes:
      - games_data:/var/lib/mysql
volumes:
  games_data: