services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: games
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: games
    ports:
      - "3306:3306"
    volumes:
      - games_data:/var/lib/mysql
  db_test:
    image: mysql
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: games_test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: games_test
    ports:
      - "3307:3306"
    volumes:
      - games_data_test:/var/lib/mysql
volumes:
  games_data:
  games_data_test: