spring:
    datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}
    main:
        allowCircularReferences: true


springdoc:
    swaggerUi:
        tagsSorter: alpha
        operationsSorter: method


api:
    security:
        token:
            secret: ${JWT_TOKEN:12345678}
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
info:
    app: Api Games
    description: Api que oferece informações de jogos e suas companhias
    github: https://github.com/Versart/apigames
