spring:
    datasource:
        url: jdbc:mysql://localhost:3306/games?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: games
        password: password
    main:
        allowCircularReferences: true

logging:
    level:
        root: info
        com:
            api:
                gamesapi: info

springdoc:
    swaggerUi:
        tagsSorter: alpha
        operationsSorter: method


api:
    security:
        token:
            secret: ${JWT_TOKEN:12345678}

management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
info:
    app: Api Games
    description: Api que oferece informações de jogos e suas companhias
    github: https://github.com/Versart/apigames
