spring:
    datasource:
        url: jdbc:mysql://localhost:3306/games?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: games
        password: password
    main:
        allowCircularReferences: true
#spring.main.allow-circular-references=true

springdoc:
    swaggerUi:
        tagsSorter: alpha
        operationsSorter: method
#springdoc.swagger-ui.operationsSorter = method

api:
    security:
        token:
            secret: ${JWT_TOKEN:12345678}
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
info:
    app: Api Games
    description: Api que oferece informações de jogos e suas companhias
    github: https://github.com/Versart/apigames
